---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  amd: true
  es6: true
  node: true
  mocha: true
globals:
  __DEVELOPMENT__: false
  __DEVTOOLS__: false
  expect: false
extends:
  - standard
  - standard-react

settings:
  import/resolver:
    webpack:
      config: webpack/webpack.config.js
