---
parser: babel-eslint
env:
  browser: true
  es6: true
globals:
  __DEVELOPMENT__: false
  expect: false
extends:
  - standard
  - standard-react
  - plugin:import/errors
  - plugin:import/warnings

settings:
  import/resolver: webpack
